### PR TITLE
Fix meteo & tv & css (soif)

### PR DESCRIPTION
**Pull request by drakaz**
Salut,

J'ai constaté que tu manquais de temps en ce moment, et comme j'ai ressortit mon nab du grenier, je voulais qu'il retrouve la fonction programme tv (perdu suite a la suppression du rss coté orange) et météo (ne fonctionnais plus avec google).

Coté météo j'ai repris le principe d'utiliser previmeteo (cf grosminet sur le forum&github) auquel j'ai rajouter la possibilité de configurer le token.

Pour le programme TV, j'ai utilisé un rss en provenance de programme-tv.net, avec au passage la mise à jour des chaines de la TNT et la possibilité d'avoir le premier programme du soir, ou les deux.

J'ai aussi mergé quelque fix divers en provenance d'autre forks ainsi que les changements CSS de soif.

J'ai fais ça rapidement, je pense pas avoir introduit de bug, je te laisse relire et voir ce que tu veux en faire :)

### CODE REVIEW

**Comment by tikismoke** [comment]
Why closing it?

**Comment by drakaz** [comment]
Not desired, I probably clicked when merging/creating PR for other patch. Reopened.

**Comment by drakaz** [comment]
Not desired, probably clicked on the wrong button while merging other things. 
By the way, soif is waiting for more than two years to be merge (css changes). I don't hope anything with this PR.

I merged soif and other stuff myself on my current fork. May be a future PR with whole changes would be better.

**Comment by tikismoke** [comment]
Strange other PR never wait so long maybe it is not stable or add bug.

**Comment by drakaz** [comment]
There is no comment on https://github.com/OpenJabNab/OpenJabNab/pull/14 so it's difficult to know why it's never merged. 

I've asked Pixel to know if it's possible for him to push it's changes and merge this PR. Let's see.

**Comment by tikismoke** [comment]
Wait and see, if i found time i'll try your repo to see diff.

**Comment by RedoXyde** [comment]
Hi,

I saw your PR last week but haven't had the time to check and merge it yet. I will have a look tonight, but it might take me a few more days before the merge (looks like there are a *lot* of changes: **+191,428** −1,614 )

Since Pixel didn't comment on the other PR, I think it's also time to review it; I guess I will start with the other one, and then review yours (which includes it anyway).

Stay tuned !

**Comment by drakaz** [comment]
Thanks RedoXyde ! It's very nice to read you. Poke me when you finished with CSS PR from soif. I'll be able to split my changes into smaller PR to make review easier.

**Comment by RedoXyde** [comment]
@drakaz: I just finished merging PR https://github.com/OpenJabNab/OpenJabNab/pull/14 in my repo (on branch [merge_pr14](https://github.com/RedoXyde/OpenJabNab/tree/merge_pr14) ).

Next steps:
- Pushing to _prod_ on my server. Check for bugs.
- Merging your PR in a new branch (merge_pr37) on my repo.
- Pushing to _prod_ on my server, again. Check for bugs, again.
- Merging my branch in the mainline (master) of this repo

I had a quick look at your PR, and most of the additions come from the PocketSphinx files in server/resources/...  I guess there is a better way to use this library (and resources) in OpenjabNab without blindly dropping 100k+ lines of data into this repo... It might require some work though; I will have a look at the code in the next few days.

**Comment by drakaz** [comment]
It's too much, i should not make a PR on master branch. This evening i'll clean the PR for first ask for weather/tv and few fixes. PocketSphinx is a huge patch which should be handle alone.

**Comment by drakaz** [comment]
Done, so now master branch (and current PR) include : 

- new design from Soif
- few fixes from https://github.com/Lyokovic/OpenJabNab
- updated weather & tv plugins
- new plugins 'blagues'
- fix record plugin

New branch https://github.com/drakaz/OpenJabNab/tree/pocketsphinx contain pocketsphinx changes. They should be much more tested and improved. I'll try to find time for this later.

**Comment by drakaz** [comment]
Close this one. Will open one PR per features/fix.

**Pull request closed without merging**
