### PR TITLE
Blagues

### PR DESCRIPTION
**Pull request by drakaz**
This a new plugins for OpenJabNab ! Let's allow our Bunny to tell some (french) jokes !

Please note that it include only good taste jokes ;)

### CODE REVIEW

**Comment by Alkorin** [comment]
Could you avoid french names in classes and filenames ?

**Comment by drakaz** [comment]
Updated PR : 
- renamed classed
- ready for translation

**Comment by Alkorin** [comment]
Is it part of the plugin http-wrapper/ps_record_0019db9edcc3_20160424_145457.wav ? :)

**Comment by drakaz** [comment]
Nop :)

**Pull request merged**
